version: "3.7"
services:
  app:
    container_name: nodeproject-mongo 
    image: nodeapi:v1
    restart: always
    build: .
    environment:
           MY_DB: mongodb://mongo_db_host:27017/employeemanagement
    ports:
      - "80:4000"   
    volumes:
      - './storage:/var/lib/docker/volumes/my-vol/_data'
    depends_on:
     - mongo
    links:
     - mongo:mongo_db_host
  mongo:
    image: mongo
    restart: always
    volumes:
        - './data:/data/db'
   